# API endpoints for data scraping
agency_api:
  urls:
    homepage: "https://www.hkp.com.hk/"
    all_estate_info: "https://data.hkp.com.hk/search/v1/estates"
    single_estate_info: "https://data.hkp.com.hk/info/v1/estates/{estate_id}"
    estate_monthly_market_info: "https://data.hkp.com.hk/info/v1/market_stat"
    building_transactions: "https://data.hkp.com.hk/info/v1/transactions/buildings/{building_id}"

  headers:
    accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
    accept_language: "zh-HK,zh;q=0.9,en-HK;q=0.8,en-US;q=0.7,en;q=0.6,zh-TW;q=0.5,zh-CN;q=0.4,ja;q=0.3"
    cache_control: "max-age=0"
    dnt: "1"
    priority: "u=0, i"
    sec_ch_ua: '"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"'
    sec_ch_ua_mobile: "?0"
    sec_ch_ua_platform: '"macOS"'
    sec_fetch_dest: "document"
    sec_fetch_mode: "navigate"
    sec_fetch_site: "none"
    sec_fetch_user: "?1"
    upgrade_insecure_requests: "1"
    user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"

wiki_api:
  urls: 
    search: "https://{language}.wikipedia.org/w/api.php"


storage:
  root_path: "data/"
  agency:
    path: "agency/"
    files:
      estate_ids: "estate_ids.txt"
      sqlite_db: "agency_data.db"
  wiki:
    path: "wiki/"
    files:
      pages: "wiki_data_partition_{num}.json"
  rag:
    path: "rag/"
    files:
      chroma_db: "chroma_db/"
      embeddings_model: "paraphrase-multilingual-MiniLM-L12-v2"
    settings:
      chunk_size: 500
      chunk_overlap: 50
      batch_size: 100
      embedding_dimensions: 384

cloudflare:
  endpoint_url: "https://{account_id}.r2.cloudflarestorage.com"
  bucket_name: "hk-housing-datahub"